//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_4_PuppyHouse1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dog()
        {
            this.NoteServices = new HashSet<NoteService>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Poroda { get; set; }
        public Nullable<int> ID_User { get; set; }
        public Nullable<int> Age { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteService> NoteServices { get; set; }
    }
}
