//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_4_PuppyHouse1.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_PuppyHouseEntities : DbContext
    {
        public BD_PuppyHouseEntities()
            : base("name=BD_PuppyHouseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<CategoryService> CategoryServices { get; set; }
        public virtual DbSet<CategoryTovar> CategoryTovars { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Dog> Dogs { get; set; }
        public virtual DbSet<NoteService> NoteServices { get; set; }
        public virtual DbSet<Postavka> Postavkas { get; set; }
        public virtual DbSet<Prodazha> Prodazhas { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<SpisokTovar> SpisokTovars { get; set; }
        public virtual DbSet<StatusEmployee> StatusEmployees { get; set; }
        public virtual DbSet<StatusNote> StatusNotes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tovar> Tovars { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
