//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_4_PuppyHouse1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteService
    {
        public int ID { get; set; }
        public Nullable<int> ID_Master { get; set; }
        public Nullable<int> ID_Dog { get; set; }
        public Nullable<int> ID_Service { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Sale { get; set; }
        public Nullable<int> ID_Status { get; set; }
        public Nullable<double> Discount { get; set; } // Новое поле для скидки
        public Nullable<double> DiscountedPrice { get; set; } // Новое поле для новой цены с учетом скидки

        public virtual Dog Dog { get; set; }
        public virtual Service Service { get; set; }
        public virtual StatusNote StatusNote { get; set; }
        public virtual User User { get; set; }
    }
}
