//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP_4_PuppyHouse1.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Postavka
    {
        public int ID { get; set; }
        public Nullable<int> ID_Tovar { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Tovar Tovar { get; set; }
    }
}
